### PR TITLE
Fix schema add

### PR DESCRIPTION
**Pull request by surendar94**
Request to add sensor name "smart-valve" in the sensor list

### CODE REVIEW

**Review by johanstokking — CHANGES_REQUESTED** [review]
Please fix the indentation, see the diff here.

Also, what is a "smart valve"? Shouldn't it be just a valve?

**Comment by surendar94** [comment]
Dear Team,

 

The device is named as “smart valve”, it has some other special functionalities apart from normal valves. 

 

So, it should be names as “smart valve”.

 

Thank you.

 

Best Regards,

Surendar S

Technical Engineer

 



AiRiCOM Middle East FZCO

Techno Point Building - Office #G-025 

PO Box 342193
Dubai Silicon Oasis, United Arab Emirates

Phone : +971 4 341 0525

Mobile : +971 54 310 9271

eMail: ***@***.*** -  <http://www.ame-iot.com/> www.ame-iot.com

**Comment by surendar94** [comment]
> Please fix the indentation, see the diff here.
> 
> Also, what is a "smart valve"? Shouldn't it be just a valve?

The device is named as “smart valve”, it has some other special functionalities apart from normal valves. 

So, it should be names as “smart valve”.

**Comment by johanstokking** [comment]
> The device is named as “smart valve”, it has some other special functionalities apart from normal valves.

Thanks. Can you elaborate on this?

The list here is a list of sensors, not devices, and not actuators. What is smart about the sensing capabilities of the valve?

**Comment by surendar94** [comment]
Dear Johan,

 

It has ability to open/close the valve at scheduled time, monitor the temperature, humidity, valve status, Tamper of the actuator, analog value if enabled, counter valve if enabled and so on.

 

Best Regards,

Surendar S

Technical Engineer

 



AiRiCOM Middle East FZCO

Techno Point Building - Office #G-025 

PO Box 342193
Dubai Silicon Oasis, United Arab Emirates

Phone : +971 4 341 0525

Mobile : +971 54 310 9271

eMail: ***@***.*** -  <http://www.ame-iot.com/> www.ame-iot.com

**Comment by johanstokking** [comment]
OK, alright. Let's do it then. Please make sure the list is sorted ascending.

**Comment by surendar94** [comment]
> OK, alright. Let's do it then. Please make sure the list is sorted ascending.

OK, i have sorted the accordingly in ascending. Kindly review and approve.

Thank you.

**Review by johanstokking — APPROVED** [review]

**Pull request merged**
